# Generated by Django 3.1.5 on 2021-02-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engine',
            old_name='oph',
            new_name='_oph',
        ),
    ]
