# Generated by Django 3.1.5 on 2021-02-02 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ]*$', 'Only letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ]*$', 'Only letters are allowed.')]),
        ),
    ]
