name: Django CI

on:
  push:
    branches: [ master, niclaus ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/ManagementSystem/
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: psycopg2 prerequisites
      run: sudo apt-get install python-dev libpq-dev
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ../../requirements.txt
    - name: Set env variables
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}
        DB_NAME=github_actions
        DB_USER=postgres
        DB_PASSWORD=postgres
        DB_HOST=127.0.0.1
        DB_PORT=5432
        DEBUG=True
        ALLOWED_HOSTS=['127.0.0.1']" > ManagementSystem/.env

    - name: Run migrations
      run: python manage.py migrate
    - name: Run Tests
      run: python manage.py test
